import type { TestPlan } from './types.js';

/**
 * Render a TestPlan to a Markdown document suitable for a human QA engineer to
 * review before any automated test generation begins.
 */
export function renderMarkdown(plan: TestPlan): string {
  const lines: string[] = [];
  const h = (s: string) => lines.push(s);

  h(`# QA Test Plan — ${plan.applicationSummary.applicationType}`);
  h('');
  h(`_Generated by ReplayQA QA Planning Engine · confidence **${plan.confidence.toFixed(2)}**_`);
  h('');

  // 1. Summary
  h('## 1. Application Summary');
  h('');
  h(`- **Type:** ${plan.applicationSummary.applicationType}`);
  h(`- **Category:** ${plan.applicationSummary.category}`);
  h(`- **Authentication required:** ${plan.applicationSummary.authenticationRequired ? 'Yes' : 'No'}`);
  h('');
  if (plan.applicationSummary.summary) {
    h(plan.applicationSummary.summary);
    h('');
  }

  // 2. Critical user journeys
  h('## 2. Critical User Journeys (prioritized)');
  h('');
  if (plan.criticalUserJourneys.length === 0) {
    h('_No journeys identified — see Missing Information._');
    h('');
  } else {
    h('| Priority | Journey | Rationale |');
    h('|----------|---------|-----------|');
    for (const j of plan.criticalUserJourneys) {
      h(`| ${emoji(j.priority)} ${j.priority} | ${esc(j.name)} | ${esc(j.rationale)} |`);
    }
    h('');
  }

  // 3. Functional scenarios
  h('## 3. Functional Test Scenarios');
  h('');
  if (plan.functionalScenarios.length === 0) {
    h('_No scenarios generated — see Missing Information._');
    h('');
  } else {
    for (const s of plan.functionalScenarios) {
      h(`### ${s.id} — ${esc(s.title)} ${emoji(s.priority)}`);
      h('');
      h(`- **Journey:** ${esc(s.journey)}`);
      h(`- **Priority:** ${s.priority}`);
      h(`- **Purpose:** ${esc(s.purpose)}`);
      if (s.preconditions.length > 0) {
      h('- **Preconditions:**');
      for (const p of s.preconditions) h(`  - ${esc(p)}`);
      }
      h(`- **Expected result:** ${esc(s.expectedResult)}`);
      h('');
    }
  }

  // 4. Edge cases
  h('## 4. Edge Cases');
  h('');
  if (plan.edgeCases.length === 0) {
    h('_None identified from the observations._');
    h('');
  } else {
    for (const g of plan.edgeCases) {
      h(`**${esc(g.area)}:**`);
      for (const c of g.cases) h(`- ${esc(c)}`);
      h('');
    }
  }

  // 5. Risk assessment
  h('## 5. Risk Assessment');
  h('');
  renderRisk(h, 'High', plan.riskAssessment.high);
  renderRisk(h, 'Medium', plan.riskAssessment.medium);
  renderRisk(h, 'Low', plan.riskAssessment.low);

  // 6. Coverage analysis
  h('## 6. Coverage Analysis');
  h('');
  h('**Areas the plan covers with confidence:**');
  if (plan.coverageAnalysis.coveredAreas.length === 0) h('- _(none)_');
  else for (const a of plan.coverageAnalysis.coveredAreas) h(`- ${esc(a)}`);
  h('');
  h('**Areas that cannot yet be evaluated:**');
  if (plan.coverageAnalysis.unevaluatedAreas.length === 0) h('- _(none)_');
  else for (const a of plan.coverageAnalysis.unevaluatedAreas) h(`- ${esc(a)}`);
  h('');

  // 7. Missing information
  h('## 7. Missing Information (Blind Spots)');
  h('');
  if (plan.missingInformation.length === 0) {
    h('_No blind spots identified._');
  } else {
    for (const m of plan.missingInformation) h(`- ${esc(m)}`);
  }
  h('');

  return lines.join('\n');
}

type Push = (s: string) => void;

function renderRisk(h: Push, label: string, items: { area: string; reason: string }[]): void {
  h(`### ${label} Risk`);
  h('');
  if (items.length === 0) {
    h('_(none)_');
    h('');
    return;
  }
  h('| Area | Why |');
  h('|------|-----|');
  for (const r of items) h(`| ${esc(r.area)} | ${esc(r.reason)} |`);
  h('');
}

function emoji(priority: string): string {
  switch (priority) {
    case 'critical': return '🔴';
    case 'high': return '🟠';
    case 'medium': return '🟡';
    case 'low': return '🟢';
    default: return '';
  }
}

/** Keep table cells and headings safe from pipe / newline breakage. */
function esc(s: string): string {
  return s.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}
